src/Entity/Lyceen.php
<?php

namespace App\Entity;

use App\Repository\LyceenRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LyceenRepository::class)]
class Lyceen
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 100)]
    private ?string $email = null;

    #[ORM\Column(length: 10)]
    private ?string $tel = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_inscription = null;

    #[ORM\OneToMany(mappedBy: 'lyceen', targetEntity: Inscription::class, orphanRemoval: true)]
    private Collection $inscriptions;

    #[ORM\ManyToOne(inversedBy: 'lyceens')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lycee $lycee = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Section $section = null;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    /**
     * @return Collection<int, Inscription>
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions->add($inscription);
            $inscription->setLyceen($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): self
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getLyceen() === $this) {
                $inscription->setLyceen(null);
            }
        }

        return $this;
    }

    public function getLycee(): ?Lycee
    {
        return $this->lycee;
    }

    public function setLycee(?Lycee $lycee): self
    {
        $this->lycee = $lycee;

        return $this;
    }

    public function getSection(): ?Section
    {
        return $this->section;
    }

    public function setSection(?Section $section): self
    {
        $this->section = $section;

        return $this;
    }
}

src/Form/LyceenType.php
<?php

namespace App\Form;

use App\Entity\Lycee;
use App\Entity\Lyceen;
use App\Entity\Section;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LyceenType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('tel')
            ->add('date_inscription')
            ->add('lycee',EntityType::class,[
                "class" => Lycee::class,
                "choice_label" => "nom"
            ])
            ->add('section',EntityType::class,[
                "class" => Section::class,
                "choice_label" => "nom"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Lyceen::class,
        ]);
    }
}

src/Controller/LyceenController.php
<?php

namespace App\Controller;

use App\Entity\Lyceen;
use App\Form\LyceenType;
use App\Repository\LyceenRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/lyceen')]
class LyceenController extends AbstractController
{
    #[Route('/', name: 'app_lyceen_index', methods: ['GET'])]
    public function index(LyceenRepository $lyceenRepository): Response
    {
        return $this->render('lyceen/index.html.twig', [
            'lyceens' => $lyceenRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_lyceen_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LyceenRepository $lyceenRepository): Response
    {
        $lyceen = new Lyceen();
        $form = $this->createForm(LyceenType::class, $lyceen);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lyceenRepository->save($lyceen, true);

            return $this->redirectToRoute('app_lyceen_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('lyceen/new.html.twig', [
            'lyceen' => $lyceen,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lyceen_show', methods: ['GET'])]
    public function show(Lyceen $lyceen): Response
    {
        return $this->render('lyceen/show.html.twig', [
            'lyceen' => $lyceen,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_lyceen_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Lyceen $lyceen, LyceenRepository $lyceenRepository): Response
    {
        $form = $this->createForm(LyceenType::class, $lyceen);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lyceenRepository->save($lyceen, true);

            return $this->redirectToRoute('app_lyceen_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('lyceen/edit.html.twig', [
            'lyceen' => $lyceen,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lyceen_delete', methods: ['POST'])]
    public function delete(Request $request, Lyceen $lyceen, LyceenRepository $lyceenRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lyceen->getId(), $request->request->get('_token'))) {
            $lyceenRepository->remove($lyceen, true);
        }

        return $this->redirectToRoute('app_lyceen_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/lyceen/_delete_form.html.twig
<form method="post" action="{{ path('app_lyceen_delete', {'id': lyceen.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lyceen.id) }}">
    <button class="btn">Delete</button>
</form>

templates/lyceen/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/lyceen/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Lyceen{% endblock %}

{% block body %}
    <h1>Edit Lyceen</h1>

    {{ include('lyceen/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_lyceen_index') }}">back to list</a>

    {{ include('lyceen/_delete_form.html.twig') }}
{% endblock %}

templates/lyceen/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lyceen index{% endblock %}

{% block body %}
    <h1>Lyceen index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Tel</th>
                <th>Date_inscription</th>
                <th>Lycee</th>
                <th>Section</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lyceen in lyceens %}
            <tr>
                <td>{{ lyceen.id }}</td>
                <td>{{ lyceen.nom }}</td>
                <td>{{ lyceen.prenom }}</td>
                <td>{{ lyceen.email }}</td>
                <td>{{ lyceen.tel }}</td>
                <td>{{ lyceen.dateInscription ? lyceen.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ lyceen.lycee.nom }}</td>
                <td>{{ lyceen.section.nom }}</td>
                <td>
                    <a href="{{ path('app_lyceen_show', {'id': lyceen.id}) }}">show</a>
                    <a href="{{ path('app_lyceen_edit', {'id': lyceen.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_lyceen_new') }}">Create new</a>
{% endblock %}

templates/lyceen/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Lyceen{% endblock %}

{% block body %}
    <h1>Create new Lyceen</h1>

    {{ include('lyceen/_form.html.twig') }}

    <a href="{{ path('app_lyceen_index') }}">back to list</a>
{% endblock %}

templates/lyceen/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lyceen{% endblock %}

{% block body %}
    <h1>Lyceen</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lyceen.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ lyceen.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ lyceen.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ lyceen.email }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ lyceen.tel }}</td>
            </tr>
            <tr>
                <th>Date_inscription</th>
                <td>{{ lyceen.dateInscription ? lyceen.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_lyceen_index') }}">back to list</a>

    <a href="{{ path('app_lyceen_edit', {'id': lyceen.id}) }}">edit</a>

    {{ include('lyceen/_delete_form.html.twig') }}
{% endblock %}